
#Solaris swap increase on global zone to 200Go

# expects param size in GB

#http://docs.oracle.com/cd/E24457_01/html/E21988/gipoj.html#scrolltoc

- debug: msg="{{size}}"

- name: Check current swap
  shell: "swap -l | grep /dev/zvol/dsk/rpool/swap | awk '{print $4}'"  # prints the actual size of rpool/swap
  register: currentswapsize

- set_fact:
     swapBadSize: false
     swapMissing: false

- set_fact:
     swapBadSize: true
  when: currentswapsize.stdout != "" and (currentswapsize.stdout|int - size|int *1024*1024*2)|abs > 20

- set_fact:
     swapMissing: true
  when: currentswapsize.stdout == ""

- name: Delete swap
  command: swap -d /dev/zvol/dsk/rpool/swap
  when:  swapBadSize and not swapMissing

#zfs set volsize=200G rpool/swap

- name: Set rpool/swap
  zfs: name=rpool/swap state=present volsize={{size}}G # volblocksize=4k not taken into account by ansible
  when: swapMissing or swapBadSize

- name: Create swap
  command: swap -a /dev/zvol/dsk/rpool/swap
  when: swapMissing or swapBadSize

